"""Added ai_mode to Greenhouse

Revision ID: 1d48d51c9e48
Revises: c85389723dc5
Create Date: 2025-12-11 15:44:39.234406

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d48d51c9e48"
down_revision: Union[str, None] = "c85389723dc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("greenhouse", sa.Column("ai_mode", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("greenhouse", "ai_mode")
    # ### end Alembic commands ###
