"""Added ai_mode to Telemetry

Revision ID: 312cc9d3f3dc
Revises: 1d48d51c9e48
Create Date: 2025-12-11 15:57:21.479826

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "312cc9d3f3dc"
down_revision: Union[str, None] = "1d48d51c9e48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telemetry", sa.Column("ai_mode", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telemetry", "ai_mode")
    # ### end Alembic commands ###
